database:
    driver: mysql
    username: env(MYSQL_USER)
    password: env(MYSQL_PASSWORD)
    databasename: env(MYSQL_DATABASE)
    host: env(MYSQL_HOST)
    port: 3306

sitename: A sample site
payoff: The amazing payoff goes here

theme: base-2016

locale: en_GB

maintenance_mode: false
maintenance_template: maintenance_default.twig

cron_hour: 3

homepage: page/1
homepage_template: index.twig

notfound: block/404-not-found

record_template: record.twig

listing_template: listing.twig
listing_records: 6
listing_sort: datepublish DESC

taxonomy_sort: DESC

search_results_template: search.twig
search_results_records: 10

add_jquery: false

recordsperpage: 10

caching:
    config: true
    templates: true
    request: false
    duration: 10
    authenticated: false
    thumbnails: true
    translations: true

changelog:
    enabled: false

thumbnails:
    default_thumbnail: [ 160, 120 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: crop
    notfound_image: bolt_assets://img/default_notfound.png
    error_image: bolt_assets://img/default_error.png
    save_files: false
    allow_upscale: false
    exif_orientation: true
    only_aliases: false

htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dt, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption, sub, super, figure, figcaption ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]

accept_file_types: [ twig, html, js, css, scss, gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg]

debug: true
debug_show_loggedoff: false
debug_permission_audit_mode: false
debug_error_level: -1               # equivalent to E_ALL
debug_error_use_symfony: false      # When set to true, Symfony Profiler will be used for exception display when possible
debug_trace_argument_limit: 4       # Determine how many steps in the backtrace will show (dump) arguments.

debuglog:
    enabled: false
    filename: bolt-debug.log
    level: DEBUG

wysiwyg:
    images: false            # Allow users to insert images in the content.
    anchor: false            # Adds a button to create internal anchors to link to.
    tables: false            # Adds a button to insert and modify tables in the content.
    fontcolor: false         # Allow users to mess around with font coloring.
    align: false             # Adds buttons for 'align left', 'align right', etc.
    subsuper: false          # Adds buttons for subscript and superscript, using `<sub>` and `<sup>`.
    embed: false             # Allows the user to insert embedded video's from Youtube, Vimeo, etc.
    underline: false         # Adds a button to underline text, using the `<u>`-tag.
    ruler: false             # Adds a button to add a horizontal ruler, using the `<hr>`-tag.
    strike: false            # Adds a button to add stikethrough, using the `<s>`-tag.
    blockquote: false        # Allows the user to insert blockquotes using the `<blockquote>`-tag.
    codesnippet: false       # Allows the user to insert code snippets using `<pre><code>`-tags.
    specialchar: false       # Adds a button to insert special chars like '€' or '™'.
    ck:
        autoParagraph: true  # If set to 'true', any pasted content is wrapped in `<p>`-tags for multiple line-breaks
        disableNativeSpellChecker: true # If set to 'true' it will stop browsers from underlining spelling mistakes
        allowNbsp: false     # If set to 'false', the editor will strip out `&nbsp;` characters. If set to 'true', it will allow them. ¯\_(ツ)_/¯

liveeditor: false

cookies_use_remoteaddr: true
cookies_use_browseragent: false
cookies_use_httphost: true

cookies_lifetime: 1209600

cookies_domain:

hash_strength: 10

compatibility:
    template_view: true
    setcontent_legacy: true
